spring:
  application:
    name: umc10th

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc10th
    username: root
    password: moonyesque1!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  token:
    secretKey: 1234567890123456789012345678901234567890123456789012345678901234
    expiration:
      access: 1800000