package com.example.umc10th.domain.mission.enums;

public enum Address {
    SEOUL, BUSAN, INCHEON, DAEGU, DAEJEON, GWANGJU, SUWON, ULSAN, SEJONG,
    GYEONGGI, GANGWON, CHUNGBUK, CHUNGNAM, JEONBUK, JEONNAM, GYEONGBUK, GYEONGNAM, JEJU
}
